import type { Metadata } from "next";
import "./globals.css";
import { ChatProvider } from "@/Store/ChatContex";
import { AuthProvider } from "@/Store/AuthContext";



export const metadata: Metadata = {
  title: "AI Chat Application",
  description: "Generated by MD Shahnawaz",
    icons:{
    icon: '/gemini-color.svg?v=2',
    }
};

export default function RootLayout({
  children,
}: Readonly<{
  children: React.ReactNode;
}>) {
  return (
    <html lang="en">
      <body >
        <AuthProvider>
         <ChatProvider>
          {children}
        </ChatProvider>
        </AuthProvider>
      </body>
    </html>
  );
}
